# Generated by Django 5.0.8 on 2026-05-04 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance_management', '0009_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_zar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_sats', models.BigIntegerField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('settled', 'Settled'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('payment_request', models.TextField(blank=True)),
                ('payment_hash', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payment_preimage', models.CharField(blank=True, max_length=255)),
                ('offramp_provider', models.CharField(blank=True, max_length=50)),
                ('offramp_reference', models.CharField(blank=True, max_length=255)),
                ('offramp_status', models.CharField(blank=True, max_length=50)),
                ('recipient_account', models.CharField(blank=True, max_length=255)),
                ('xrpl_hash', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lightning_payments', to='compliance_management.bank')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lightning_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lightning Payment',
                'verbose_name_plural': 'Lightning Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bank', 'status'], name='payment_man_bank_id_4d673a_idx'), models.Index(fields=['payment_hash'], name='payment_man_payment_f83483_idx')],
            },
        ),
    ]
