# Generated by Django 5.0.8 on 2025-11-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_management', '0002_alter_bank_options_bank_updated_at_bank_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_documents', to='compliance_management.bank')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance_management.isoreconciliationlog')),
            ],
        ),
    ]
