# Generated by Django 5.0.8 on 2025-12-27 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_management', '0003_isodocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message_type', models.CharField(max_length=20)),
                ('version', models.CharField(default='001.08', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('requires_structured_remittance', models.BooleanField(default=False)),
                ('allows_unstructured_remittance', models.BooleanField(default=True)),
                ('max_remittance_length', models.IntegerField(default=140)),
                ('strict_schema_validation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISOFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('regex', models.CharField(blank=True, max_length=255)),
                ('iso_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='compliance_management.isoprofile')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='iso_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='compliance_management.isoprofile'),
        ),
        migrations.AddField(
            model_name='isoreconciliationlog',
            name='iso_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance_management.isoprofile'),
        ),
    ]
