# Generated by Django 5.0.8 on 2025-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_management', '0005_alter_bank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='is_active',
        ),
        migrations.AddField(
            model_name='isoprofile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
