# Generated by Django 5.0.8 on 2025-12-27 17:04


from django.db import migrations

def create_default_iso_profile(apps, schema_editor):
    ISOProfile = apps.get_model('compliance_management', 'ISOProfile')

    if not ISOProfile.objects.filter(is_default=True).exists():
        ISOProfile.objects.create(
            name="SWIFT_CBPR_PLUS",
            message_type="pacs.008",
            version="001.08",
            is_default=True,
            requires_structured_remittance=True,
            allows_unstructured_remittance=False,
            max_remittance_length=140,
            strict_schema_validation=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('compliance_management', '0006_remove_bank_is_active_isoprofile_is_default'),
    ]

    operations = [
        migrations.RunPython(create_default_iso_profile),
    ]
