# Generated by Django 5.0.8 on 2026-04-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_management', '0007_seed_default_iso_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isofieldrule',
            options={'verbose_name': 'ISO Field Rule', 'verbose_name_plural': 'ISO Field Rules'},
        ),
        migrations.AlterModelOptions(
            name='isoprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'ISO Profile', 'verbose_name_plural': 'ISO Profiles'},
        ),
        migrations.AddField(
            model_name='bank',
            name='bic',
            field=models.CharField(blank=True, help_text='Bank Identifier Code (SWIFT BIC), e.g. ABSAZAJJ', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='isofieldrule',
            name='weight',
            field=models.IntegerField(default=1, help_text='Violation severity weight for compliance score calculation (1=low, 5=critical)'),
        ),
        migrations.AddField(
            model_name='isoprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='isofieldrule',
            unique_together={('iso_profile', 'field_path')},
        ),
    ]
