# Generated by Django 5.0.8 on 2026-05-01 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_management', '0008_alter_isofieldrule_options_alter_isoprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('end_user', 'End User'), ('analyst', 'Analyst'), ('auditor', 'Auditor'), ('institution_admin', 'Institution Admin'), ('super_admin', 'Super Admin')], default='analyst', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, help_text='Null only for SUPER_ADMIN', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='compliance_management.bank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
    ]
